channels:
 - conda-forge  
 - defaults
  
dependencies:
  - python=3.6.7
  - numpy=1.18.5
  - pandas=1.1.5
  - scikit-learn=0.23.1
  - Pillow
  - pip
  - pip:
    - polyaxon-cli==0.5.6
    - tensorflow==2.0.0
    - Flask==1.1.2
    - gunicorn==20.1.0
    - h5py==2.10.0
